import { UserRole } from 'src/auth/enums/user-role.enum'; // Ajusta la ruta a tu enum

export const SEED_USERS = [
  {
    fullName: 'Mike Mahan',
    email: 'mmahan13@gmail.com',
    password: '@Migmah13', // El servicio se encargará de encriptarla
    roles: [UserRole.ADMIN],
  },
  {
    fullName: 'Manuel Fernández Caballero',
    email: 'mielfuentesburgos@gmail.com',
    password: '@ManuFernendezC2026',
    roles: [UserRole.USER],
  },
];

export const SEED_COMPANY = {
  businessName: 'Sabor a Miel S.L.',
  taxId: '71301134F',
  address: 'C/ dos de mayo, 20 - 5°A 09006 Burgos',
  bankAccount: 'ES91 1234 5678 9012 3456 7890',
  phone: '680849714',
};

export const SEED_TAXES = [
  { label: 'Exento de IVA (0%)', iva: 0, surcharge: 0 },
  { label: 'IVA Superreducido (4%)', iva: 4, surcharge: 0 },
  { label: 'IVA Reducido (10%)', iva: 10, surcharge: 0 },
  { label: 'IVA General (21%)', iva: 21, surcharge: 0 },
  { label: 'IVA Reducido + RE (10% + 1.4%)', iva: 10, surcharge: 1.4 },
  { label: 'IVA General + RE (21% + 5.2%)', iva: 21, surcharge: 5.2 },
];

export const SEED_PRODUCTS = [
  { productName: 'A ACIDO FORMICO 60 PAQUETE', basePrice: 119 },
  { productName: 'A BLUSONES TELA FINA', basePrice: 30 },
  {
    productName: 'A BOTE V720 DE 950GR PARA ENVASAR MIEL MIA',
    basePrice: 0.24,
  },
  { productName: 'A BOTES 950G BAJO', basePrice: 0.16 },
  { productName: 'A BOTES A370 500GR', basePrice: 0.2 },
  { productName: 'A TAPAS BOTES 500GR', basePrice: 0.04 },
  { productName: 'A TIRAS CARTON 100 UNIDADES', basePrice: 5 },
  { productName: 'AZ500 MIEL DE AZAHAR 500 GR.', basePrice: 2.6 },
  { productName: 'AZ950 MIEL DE AZAHAR 950 GR.', basePrice: 4.75 },
  { productName: 'AZKG MIEL DE AZAHAR KG.', basePrice: 4.95 },
  { productName: 'BI450 MIEL DE BIERCOL 450 GR.', basePrice: 2.4 },
  { productName: 'BO450 MIEL DE BOSQUE 450 GR.', basePrice: 2.4 },
  { productName: 'BO500 MIEL DE BOSQUE 500 GR.', basePrice: 2.75 },
  { productName: 'BO950 MIEL DE BOSQUE 950 GR.', basePrice: 5 },
  { productName: 'BOGRANEL MIEL DE BOSQUE GRANEL', basePrice: 4.9 },
  { productName: 'BR35 MIEL DE BREZO 35 GR.', basePrice: 0 },
  { productName: 'BR450 MIEL DE BREZO 450 GR.', basePrice: 2.4 },
  { productName: 'BR500 MIEL DE BREZO 500 GR.', basePrice: 2.75 },
  { productName: 'BR950 MIEL DE BREZO 950 GR.', basePrice: 5 },
  { productName: 'BRKG MIEL DE BREZO KG.', basePrice: 0 },
  { productName: 'BRGRANEL MIEL DE BREZO GRANEL', basePrice: 4.8 },
  { productName: 'EN500 MIEL DE ENCINA 500 GR.', basePrice: 0 },
  { productName: 'EN950 MIEL DE ENCINA 950 GR.', basePrice: 0 },
  { productName: 'ENKG MIEL DE ENCINA KG.', basePrice: 5.2 },
  { productName: 'EU500 MIEL DE EUCALIPTO 500 GR.', basePrice: 3 },
  { productName: 'EU950 MIEL DE EUCALIPTO 950 GR.', basePrice: 0 },
  { productName: 'EUKG MIEL DE EUCALIPTO KG.', basePrice: 5.5 },
  { productName: 'LA450 MIEL DE LAVANDA 450 GR.', basePrice: 2.4 },
  { productName: 'LA500 MIEL DE LAVANDA 500 GR.', basePrice: 2.6 },
  { productName: 'LA950 MIEL DE LAVANDA 950 GR.', basePrice: 5 },
  { productName: 'LAC500 MIEL DE LAVANDA CREMA 500 GR.', basePrice: 2.8 },
  { productName: 'LACKG MIEL DE LAVANDA CREMA KG.', basePrice: 5.15 },
  { productName: 'LI500 MIEL DE LIMON 500 GR.', basePrice: 0 },
  { productName: 'LI950 MIEL DE LIMON 950 GR.', basePrice: 0 },
  { productName: 'LIKG MIEL DE LIMON KG', basePrice: 0 },
  { productName: 'MI500 MIEL DE MILFLORES 500 GR.', basePrice: 2.4 },
  { productName: 'MI950 MIEL DE MILFLORES 950 GR.', basePrice: 4.25 },
  { productName: 'MIGRANEL MIEL DE MILFLORES GRANEL', basePrice: 3.95 },
  { productName: 'MIKG MIEL DE MILFLORES KG.', basePrice: 4.35 },
  { productName: 'MÑ500 MIEL DE MONTAÑA 500 GR.', basePrice: 2.65 },
  { productName: 'MÑ950 MIEL DE MONTAÑA 950 GR.', basePrice: 5.15 },
  { productName: 'MÑKG MIEL DE MONTAÑA KG.', basePrice: 5.25 },
  { productName: 'PO230 POLEN 230 GR.', basePrice: 3 },
  { productName: 'POLEN KG. GRANEL', basePrice: 11.6 },
  { productName: 'RO500 MIEL DE ROMERO 500 GR.', basePrice: 2.75 },
  { productName: 'RO950 MIEL DE ROMERO 950 GR.', basePrice: 5.2 },
  { productName: 'ROC500 MIEL DE ROMERO CREMA 500 GR.', basePrice: 3 },
  { productName: 'ROGRANEL MIEL DE ROMERO GRANEL', basePrice: 5 },
  { productName: 'TO500 MIEL DE TOMILLO 500 GR.', basePrice: 2.6 },
  { productName: 'TO950 MIEL DE TOMILLO 950 GR.', basePrice: 4.9 },
  { productName: 'TOGRANEL MIEL DE TOMILLO GRANEL', basePrice: 4.75 },
  { productName: 'TOKG MIEL DE TOMILLO KG.', basePrice: 0 },
  { productName: 'VMAL MIEL CON ALMENDRAS FRASCO 280', basePrice: 0 },
  { productName: 'VMAV MIEL CON AVELLANAS FRASCO 280', basePrice: 0 },
  { productName: 'VMCA MIEL CON CACAO FRASCO 280', basePrice: 0 },
  { productName: 'VMNU MIEL CON NUECES FRASCO 280', basePrice: 0 },
  { productName: 'VJA20 JALEA REAL 20 GR', basePrice: 0 },
];

export const SEED_CLIENTS = [
  {
    businessName: 'PANADERIA JOSEFA BLANDON DAVILA',
    taxId: '14560411Y',
    phone: '',
    address: 'C/ ALDABE, 22 BAJO, 01012 Vitoria-Gasteiz (Álava)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'BLANCA RÍOS MARTÍNEZ',
    taxId: '24400974K',
    phone: '',
    address: 'C/ DONOSTI, 11, 01010 Vitoria Gasteiz (Álava)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'CARNICERÍA AMADO S.L.',
    taxId: 'B01436724',
    phone: '',
    address: 'C/ JUNTAS GENERALES, 29, 01011 Vitoria Gasteiz (Álava)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'EL CAMPO SELECCIÓN S.C',
    taxId: 'J75554816',
    phone: '',
    address: 'C/ PEDRO EGAÑA, 2, 01001 Vitoria Gasteiz (Álava)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'FRUTERÍA GURELANDA',
    taxId: 'J42925172',
    phone: '',
    address: 'C/ PRADO, 4, 01005 Vitoria Gasteiz (Álava)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'HÉCTOR GONZALO PEÑALVER RÍOS',
    taxId: '72730492F',
    phone: '',
    address: 'PORTAL DE FORONDA, 24 BAJO, 01010 Vitoria (Álava)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'JORGE CAMPOMAR SAGREDO',
    taxId: '44678551Q',
    phone: '',
    address: 'C/ ARGENTINA, Nº1, 01009 Vitoria-Gasteiz (Álava)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'LAMOUSSA BERE, S. L.',
    taxId: 'B19766971',
    phone: '',
    address:
      'C/ CORONACION DE LA VIRGEN BLANCA, 5, 01012 Vitoria-Gasteiz (Álava)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'LARRABIDE SOLA, S. L.',
    taxId: '01292432B',
    phone: '',
    address: 'C/ BADAYA, 22, Vitoria-Gasteiz (Álava)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'MAQUIE ROSE, SC',
    taxId: 'J01554476',
    phone: '',
    address: 'CORONACION, 01012 Vitoria (Álava)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'MARÍA PINO PEREZ ALONSO',
    taxId: '12386816M',
    phone: '',
    address:
      'C/ NIEVES CANO, 1 Nº13 MERCADO DE HEBILLAS, 01006 Vitoria (Álava)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'OROFILA GONZALEZ FRAILE',
    taxId: '16292327R',
    phone: '',
    address: 'C/ REYES DE NAVARRA, 37 BAJO, 01013 Vitoria Gasteiz (Álava)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'PEDRO VAZQUEZ VAZQUEZ',
    taxId: '16271069H',
    phone: '',
    address: 'C/ PORTAL DE CASTILLA, 40, 01007 Vitoria-Gasteiz (Álava)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'RAFA PASADAS S. C.',
    taxId: 'J01541036',
    phone: '',
    address: 'C/ JESUS GURIDI, 1 A, 01004 Vitoria-Gasteiz (Álava)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'ROBERTO MARTINEZ ALEGRIA ELORRIETA',
    taxId: '16286685V',
    phone: '',
    address: 'C/ CUBA, 3 BAJO, Vitoria-Gasteiz (Álava)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'SUPERMERCADOS ISABELLA COVIRAN LURRA FRESCOA S L',
    taxId: 'B01581396',
    phone: '',
    address:
      'SUPERMERCADOS ISABELLA COVIRAN LURRA FRESCOA S L, Vitoria (Álava)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'MANUEL GUTIERREZ CORRALES',
    taxId: '15505797W',
    phone: '',
    address: 'C/ FÉLIZ SEGURA RICCI, 4, 33500 Llanes (Asturias)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'AUTOSERVICIOS MAFER S L',
    taxId: 'B09253618',
    phone: '',
    address: 'AV BURGOS, 10, 09250 Belorado (Burgos)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'ALIMENTACION JESUS- JESUS MARIA CALZADA',
    taxId: '13114088V',
    phone: '',
    address: 'C/ PADRE ARAMBURU Nº 2 BAJO, 09006 Burgos (Burgos)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'ALIMENTACION SAN LESMES',
    taxId: '13144816V',
    phone: '',
    address: 'C/ LUIS ALBERDI 46, Burgos (Burgos)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'ALINA MARÍA AXENTE',
    taxId: 'X4220395X',
    phone: '',
    address: 'C/ SAN PERO Y SAN FELICES. 33, 09001 Burgos (Burgos)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'ANA MARÍA SOTO LOSADA',
    taxId: '13127721B',
    phone: '',
    address: 'C/ FEDERICO GARCÍA LORCA, Nº4, 09007 Burgos (Burgos)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'BEGOÑA ORTEGA ALONSO',
    taxId: '13102905N',
    phone: '',
    address: 'C/ SAN PEDRO Y SAN FELICES, 33, 09001 Burgos (Burgos)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'CASA QUINTANILLA',
    taxId: '13069137P',
    phone: '',
    address: 'C/ LA PALOMA, 17, 09003 Burgos (Burgos)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'CHARCUTERIA CABIA S. L.',
    taxId: 'B09253220',
    phone: '',
    address: 'C/ FRONTÓN 2, 2A, 09007 Burgos (Burgos)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'COMERCIALIZADORA DE DIOS DE LA RIVERA SL',
    taxId: 'B47436118',
    phone: '',
    address: 'C/ LA PUEBLA Nº38, 09004 Burgos (Burgos)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'DISTRIBUCIONES ALIMENTARIAS J.R.TEMIÑO SL',
    taxId: 'B75723486',
    phone: '629417752',
    address: 'POL. IND. INBISA VILLAFRIA NAVES 3 E, 09007 Burgos (Burgos)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'ELENA SANCHO ALVAREZ',
    taxId: '13115060T',
    phone: '',
    address: 'C/ SANTA CLARA, 51, 09002 Burgos (Burgos)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'FUNDACIÓN CIRCULO BURGOS',
    taxId: 'G09000779',
    phone: '',
    address: 'PLAZA ESPAÑA, 3 BAJO, 09005 Burgos (Burgos)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'GUILLERMO ARCE GUTIERREZ',
    taxId: '13095511R',
    phone: '',
    address: 'C/ DIEGO LAINEZ, 10, 09005 Burgos (Burgos)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'INMACULADA BARRIO HERNANDO',
    taxId: '13108834F',
    phone: '',
    address: 'C/ DIEGO LAINEZ, 10, 09005 Burgos (Burgos)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'JAIME RUIZ GONZALEZ SL',
    taxId: 'B09594219',
    phone: '',
    address: 'AVDA. CONSTITUCIÓN ESPAÑOLA Nº 33, 09007 Burgos (Burgos)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'JOCAMA ALIMENTACION',
    taxId: 'B99441098',
    phone: '',
    address: 'C/ CAÑAMAR Nº4, 09007 Burgos (Burgos)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'LA MOLIENDA S C',
    taxId: 'J05298401',
    phone: '',
    address: 'C/ LA PALOMA, 18, 09003 Burgos (Burgos)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'LAURA VILLANUEVA ARCEREDILLO',
    taxId: '71274011R',
    phone: '',
    address: 'C/ SAN BRUNO, 6, 09007 Burgos (Burgos)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'MARÍA ASCENSION SANCHO DELGADO',
    taxId: '13123380V',
    phone: '',
    address: 'C/ VALDENUÑEZ, Nº 4 BAJO, 09001 Burgos (Burgos)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'MARIA BASCONES LOUAZO',
    taxId: '71263441B',
    phone: '',
    address:
      'Mercado Norte Municipal Pje. De Radio Popular, 21, 09005 Burgos (Burgos)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'MARÍA DEL PILAR DÍEZ CELIS',
    taxId: '13157708Y',
    phone: '',
    address: 'C/ CARRETERA ARCOS, Nº 2, 09001 Burgos (Burgos)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'MARIA JOSEFA FRESCO - ALIMENTACIÓN CRESFER',
    taxId: '13104423N',
    phone: '',
    address: 'C/ CONDESA MENCIA 108, 09006 Burgos (Burgos)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'MARIA TERESA MANRIQUE SANCIBRIAN FRUTAS Y VERDURAS TERE',
    taxId: '13114837F',
    phone: '',
    address: 'AVENIDA REYES CATÓLICOS, 34, 09005 Burgos (Burgos)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'MARÍA YOLANDA ANTÓN DELGADO',
    taxId: '13131277W',
    phone: '',
    address: 'C/ CALZADAS, 5, 09004 Burgos (Burgos)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'MOKATAZITAS S. L.',
    taxId: '09577024B',
    phone: '',
    address: 'C/ SANTIAGO, 22, 09007 Burgos (Burgos)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'ROMAN TEMIÑO',
    taxId: '13142170Q',
    phone: '629417752',
    address:
      'C /VITORIA 305 PARQUE EMPRESARIAL INBISA VILLAFRIA, 09007 Burgos (Burgos)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'SALVADOR BRAVO DURÁN',
    taxId: '25576968W',
    phone: '',
    address: 'C/ CONCEPCIÓN, 2, 09002 Burgos (Burgos)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'SANTA JULITA, S.L.',
    taxId: 'B16752552',
    phone: '',
    address: 'FINCA SAN QUIRCE, S/N, 09194 Los Ausines (Burgos)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'SUPERBURGOS',
    taxId: 'J09394859',
    phone: '',
    address: 'C/ BARTOLOME ORDOÑEZ 4, Burgos (Burgos)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'TERESA ANTON DELGADO',
    taxId: '13137725X',
    phone: '',
    address: 'C/ SANTA CRUZ, 12 BAJO, 09002 Burgos (Burgos)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'JOSE GERARO GOMEZ PARRA',
    taxId: '03234619Z',
    phone: '',
    address: 'C/ MAYOR, 51, 09245 Grisaleña (Burgos)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'ESPECIALIDADES LA MIRANDESA, S. L.',
    taxId: 'B09290065',
    phone: '',
    address: 'CARRETERA N-1, Nº 69-71, 09200 Miranda de Ebro (Burgos)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'ROSA MARICELA ERRAIZ VARGAS',
    taxId: '71380994B',
    phone: '',
    address: 'C/ CLAVEL 10 DP., 09200 Miranda de Ebro (Burgos)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'A.P.G. COMERCIAL PALENCIA S.L.',
    taxId: 'B09299389',
    phone: '676475606',
    address: 'C/ LOS ALTOS 6, 09550 Villarcayo (Burgos)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'LUIS SOTO GARCÍA',
    taxId: '13933743K',
    phone: '',
    address: 'C/ MATILDE DE LA TORRE Nº 9, 39500 Cabezón de la Sal (Cantabria)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'CABOTEJA S.L.',
    taxId: 'B39457924',
    phone: '',
    address:
      'EL SOLARON 13, 39150 Castanedo (ESTACION DE SERVICIO) (Cantabria)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'FRUTAS Y EMBUTIDOS LUENGO',
    taxId: '13774990Z',
    phone: '',
    address: 'C/ LOS CIRUELOS, 33, 39011 El Alisal, Santander (Cantabria)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'FRANCISCO JAVIER LOMILLOS- CARNICERÍA LOMILLOS S. L.',
    taxId: 'B39236708',
    phone: '942541642',
    address: 'C/ TOMAS BRETÓN Nº9, 39610 El Astillero (Cantabria)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'FRANCISCO JAVIER AGUADO',
    taxId: '16266760X',
    phone: '',
    address: 'C/ PEÑOTA, Nº 1, 39160 Laredo (Cantabria)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'FRESH FRUITS SC',
    taxId: 'J09684671',
    phone: '',
    address: 'AVDA ESPAÑA, Nº16 PLANTA BAJA, 39770 Laredo (Cantabria)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'OLIVER SOMARRIBA',
    taxId: '72038460P',
    phone: '',
    address: 'AVENIDA SANTANDER Nº 28, Noja (Cantabria)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'CARNICERÍA SOLAR-ENRIQUE SOLAR LÓPEZ',
    taxId: '72030985E',
    phone: '',
    address: 'C/ MAYOR, 32, 39200 Reinosa (Cantabria)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'PEDRO SAIZ GUTIERREZ S. L.',
    taxId: '39790308B',
    phone: '',
    address:
      'BARRIO CURELLE, 6 BAJO, 39292 Requejo, Campoo de En Medio (Cantabria)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'Mª CARMEN GUTIERREZ BENGOCHEA',
    taxId: '72092023H',
    phone: '',
    address: 'C/ MERCADO, 15, 39540 San Vicente de la Barquera (Cantabria)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName:
      'SERGIO CUETO GONZALEZ- CARNICERIA FERMIN SAN VICENTE DE LA BARQUERA',
    taxId: '72125967Z',
    phone: '',
    address: 'PLAZA ABASTOS, 39540 San Vicente de la Barquera (Cantabria)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'ANA ISABEL LOPEZ ARSUAGA -SANTANDER- BIEN APARECIDA-',
    taxId: '13781067L',
    phone: '686876241',
    address: 'C/ VARGAS, 67, 39010 Santander (Cantabria)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'ARACELI MORENO GOMEZ',
    taxId: '13772786H',
    phone: '',
    address: 'C/ PERINES Nº19, Santander (Cantabria)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'ENRIQUE BARQUIN CALDERON',
    taxId: '13914094Z',
    phone: '',
    address: 'C/ ESCULTOR TEODORO CALDERON, 13900 Santander (Cantabria)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'GEMA NAVARES RUIZ',
    taxId: '13757734P',
    phone: '',
    address: 'MERCADO DE LA ESPERANZA PUESTO 15, 39002 Santander (Cantabria)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'GONZALO SALCEDA QUINTANA',
    taxId: '13738220K',
    phone: '',
    address: 'C/ SAN MARTIN DEL PINO Nº5 BAJO, Santander (Cantabria)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'JESUS BASCONES RUEDA',
    taxId: '72118201E',
    phone: '',
    address: 'C/ SAN LUIS 34, Santander (Cantabria)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'JULIAN GARCÍA PEREZ',
    taxId: '20215148B',
    phone: '',
    address: 'C/ ALTA, 64, 39008 Santander (Cantabria)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'LA ABECERIA DE SECRETOS DE CHEF S. C.',
    taxId: 'J05376645',
    phone: '',
    address:
      'C/ MARCELINO SANZ DE SAUTUOLA, 11 BAJO, 39003 Santander (Cantabria)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'LA GALLOFA PANADERIAS ESPECIALIZADAS S.L.',
    taxId: 'B39535661',
    phone: '',
    address: 'POL. NUEVA MONTAÑA NAVE 61, Santander (Cantabria)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'MANUEL ALONSO COBO',
    taxId: '13776839T',
    phone: '',
    address: 'C/ GENERAL DAVILA, 314, 39007 Santander (Cantabria)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'MARÍA TERESA TEGLA GOMEZ',
    taxId: '13738042G',
    phone: '',
    address: 'C/ GENERAL DÁVILA, 26, 39005 Santander (Cantabria)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'VIVO ENTR3OLIVOS SL',
    taxId: 'B16881641',
    phone: '',
    address: 'C/ PEÑA HERBOSA 11, 4 IZQ, 39003 Santander (Cantabria)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'ANTONIO ELIZAGARAY LARUMBE',
    taxId: '15809729N',
    phone: '',
    address: 'C/ LOS CLAVELES, 8 TABERNA ALBERTO, 39740 Santoña (Cantabria)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'ESTEBAN BADIOLA CASTELLOT',
    taxId: '20194764M',
    phone: '',
    address: 'C/ MARINOS DE SANTOÑA, 6, 39740 Santoña (Cantabria)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'EL MARRUBIO ALIMENTACIÓN SL',
    taxId: '39656020B',
    phone: '',
    address: 'C/ EL SOTO Nº4, 39300 Torrelavega (Cantabria)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'ELENA MARTINEZ HARO',
    taxId: '20217956J',
    phone: '',
    address: 'C/ JUAN XXIII, 14, 39300 Torrelavega (Cantabria)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'MOHAMED LAAZAIRI',
    taxId: 'X2627257J',
    phone: '',
    address: 'C/ JUAN XXIII, 11 BAJO 4, 39300 Torrelavega (Cantabria)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'TRINIDAD DE DIOS PEÑA',
    taxId: '13782768H',
    phone: '',
    address: 'C/ JOSE MARÍA PEREDA, 49, 39300 Torrelavega (Cantabria)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'MOSTEIRO S.L.',
    taxId: '48609580B',
    phone: '',
    address:
      'POL. TRAPAGA Nº 5. CTRA. SAN VICENTE S/N, 48510 Trapagaran (Cantabria)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'HIPOLITO VIDAL GUTIERREZ-UNQUERA',
    taxId: '13757832Z',
    phone: '',
    address: 'C/ SAN FELIPE NERI 4, 39560 Unquera (Cantabria)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'TIENDA VILLASOLA S.L.',
    taxId: '39794243B',
    phone: '',
    address: 'C/ CARRETERA GENERAL 20, 39560 Unquera (Cantabria)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'PESCADOS ORIOMAR S.L.',
    taxId: 'B20703997',
    phone: '',
    address: 'EUSKO GUDARI KALEA Nº 46 DP, 20810 Orio (Guipúzcoa)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'PECADO GOURMET S.L.',
    taxId: 'B56637085',
    phone: '',
    address: 'C/ NICOLASA GOMEZ, 24, 28022 Madrid (Madrid)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'ELIANE DE SOUZA MEDINA - EL COLMADO DE ERMITAGAÑA',
    taxId: '73142152J',
    phone: '',
    address: 'C/ ERMITAGAÑA, 4 PUESTOS 12-13, 31008 Pamplona (Navarra)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'ELINE DE SOUZA MEDINA- COMESTIBLES IBAÑEZ',
    taxId: 'X5917902W',
    phone: '',
    address: 'GRUPO RINALDI, 25, 31007 Pamplona (Navarra)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'CARLOS JOSÉ ALEJOS FAJARDO',
    taxId: '72379257M',
    phone: '',
    address: 'PLAZA ESPAÑA, Nº 6 BAJO, 34800 Aguilar de Campoo (Palencia)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'NACHO EN COCINASUPERMERCADOS CENICERO S L',
    taxId: 'B26240937',
    phone: '',
    address: 'C/ MARTÍIN BASTIDA, 4, Cenicero (La Rioja)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'CELIA RENUNCIO CALVO',
    taxId: '71351559Q',
    phone: '',
    address: 'PLAZA CASTAÑARES BAJO TIENDA HIPERFRUTA, Haro (La Rioja)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'ALAIN LARREA LAMBARRI',
    taxId: '78925719T',
    phone: '',
    address: 'C/ EL COSO, 19 BAJO, 26140 Lardero (La Rioja)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'ANA DELIA PASCUAL BENITO',
    taxId: '16546411G',
    phone: '',
    address: 'C/ CAPITAN GALLARZA, 9 BAJO, 26001 Logroño (La Rioja)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'CAFÉ ELECTI SL',
    taxId: 'B13770821',
    phone: '',
    address: 'AVENIDA PEREZ GALDOS, 43 BAJO, 26002 Logroño (La Rioja)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'JORGE ARTURO CASTAÑO GALLEGO',
    taxId: '17496438Q',
    phone: '',
    address: 'C/ REPUBLICA ARGENTINA, 11 BAJO, 26002 Logroño (La Rioja)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'JOSE IGNACIO FERNANDEZ GARCIA',
    taxId: '16577973X',
    phone: '',
    address: 'C/ LARDERO, 13 BIS BAJO, Logroño (La Rioja)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'OLIVER CASIS ALLO',
    taxId: '16560898R',
    phone: '',
    address: 'C/ PRADEJÓN, 3 1ºA, Logroño (La Rioja)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'SABOREA GOURMET',
    taxId: '18084462E',
    phone: '',
    address: 'AVD. CLUB DEPORTIVO, 92 BAJO, Logroño (La Rioja)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'JESUS BERGES AGUIRRE',
    taxId: '16574454X',
    phone: '',
    address: 'C/ CTRA. DE LOGROÑO, 53, 26370 Navarrete (La Rioja)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'ALNATURAL SC',
    taxId: 'J01945914',
    phone: '',
    address: 'C/ LAS PARRAS, 32, 26142 Villamediana de Iregua (La Rioja)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'DIETETICA LAGUNA S L',
    taxId: 'B19432855',
    phone: '',
    address: 'AVENIDA MADRID, 51, 47140 Laguna de Duero (Valladolid)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'AURA UREÑA',
    taxId: '60708063T',
    phone: '',
    address: 'C/ VELAZQUEZ, 10, 48902 Baracaldo (Vizcaya)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'CARNICERIA CHARCUTERIA RICARDO S. L.',
    taxId: 'B95668463',
    phone: '',
    address: 'AVENIDA LA LIBERTAD, 46, 48901 Baracaldo (Vizcaya)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'ELGARBIDEAK S.L.',
    taxId: 'B95189460',
    phone: '',
    address: 'C/ BIZKAIA, Nº 28, 48901 Baracaldo (Vizcaya)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'KAREN MARIANA ROMERO FLORES Y OTRO SOCIEDAD CIVIL',
    taxId: 'J75836940',
    phone: '',
    address: 'C/ MERINDAD DE URIBE, 12, 48910 Baracaldo (Vizcaya)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'MARIA DIEZ ROMERO',
    taxId: '78935227D',
    phone: '',
    address: 'C/ MERINDAD DE URIBE 12, 48901 Baracaldo (Vizcaya)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'EVELYN RODRIGUEZ MENDEZ',
    taxId: '78923223B',
    phone: '',
    address: 'C/ ESPALZA, 3, 48007 Bilbao (Vizcaya)',
    hasEquivalenceSurcharge: false,
  },
  {
    businessName: 'JUAN CARLOS PARRAGA ANDIA',
    taxId: '16108001C',
    phone: '',
    address: 'C/ MATIKO, 4, 48007 Bilbao (Vizcaya)',
    hasEquivalenceSurcharge: false,
  },
];
